apiVersion: v1
kind: Service
metadata:
  name: db
  label:
    name: mysql-service
    app : myapp

spec:
    ports: 
        - port: 80
          targetPort: 80
    selector:
     name: mysql-pod
     app: myapp